### ISSUE TITLE
ファイルアップロード中にLoadingのトーストが表示されない

### ISSUE THREAD

**Issue by oka4shi** [sohosai/sos24-client#299]

**Comment by naohanpen** [comment]
@oka4shi トーストのライブラリってすでに入ってます？🙏🏻

**Comment by oka4shi** [comment]
@naohanpen 
>  トーストのライブラリってすでに入ってます？🙏🏻

入ってます！
この辺りを参考に修正してもらえるとありがたいです。難しそうだったら教えてください。

https://github.com/sohosai/sos24-client/blob/19b1c96fa8bb9b817f3132bdad93e90f6b59c148/src/common_components/project/ProjectView.tsx#L61-L86

**Comment by ishikawa-naota** [comment]
分かりました。ありがとうございます！

**Comment by ishikawa-naota** [comment]
### メモ
- トースト
  - https://react-hot-toast.com/docs/toast
- ラッパーによって Promise がなくなってる？
  - 強引に実装 ```toast.***()```
  - ラッパーを Promise 化？

**Comment by naohanpen** [comment]
- 申請作成・編集（実委用）、お知らせ作成・編集（実委用）は対応済み
- 申請回答作成・編集（企画/実委用）は https://github.com/sohosai/sos24-client/issues/444 で対応
