### ISSUE TITLE
申請編集で添付ファイルを変更しても反映されない

### ISSUE THREAD

**Issue by oka4shi** [sohosai/sos24-client#392]

**Comment by arata-nvm** [comment]
これって今誰がボールを持っていて、どんな状況ですか？

**Comment by naohanpen** [comment]
@arata-nvm 
自分です！ごめんなさい💦
解決策は分かっていたのですが、定期試験で忘れてました💦

**Comment by naohanpen** [comment]
- 編集ページのデフォルト値にファイルが予期しない形で渡されている
  - ```{"title":"申請太郎","description":"せつめい","starts_at":"2000-01-01T01:01","ends_at":"9999-09-09T00:00","categories":["foods_with_kitchen"],"attributes":["academic"],"attachments":["c1a960c9-afe3-48a2-8f32-b86ca0774804"],"items":[]}```
  - https://github.com/sohosai/sos24-client/blob/f672388adfc047d9a4354f649cc7c5235957e640/src/app/committee/forms/%5Bform_id%5D/edit/page.tsx#L105

**Comment by naohanpen** [comment]
- FormEditor コンポーネントは、新規作成と編集で共通
  - onSubmit でファイルのアップロードを行っているため、更新時はその処理を外せばいい
    - ファイルの編集も考えると、そもそも随時アップロードして (u)id のみを送信すればいい

**Comment by arata-nvm** [comment]
了解です、状況説明助かります！　ありがとうございます:bow:
忙しいとかがあれば他の人にタスクを回すなどができるので、気軽に相談ください

**Comment by naohanpen** [comment]
今更ですが、根本的には PUT しても更新されないバックグラウンドの問題でした。
https://github.com/sohosai/sos24-server/issues/320
